version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: keyuser
      POSTGRES_PASSWORD: keypass123
      POSTGRES_DB: keydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: